name: cbn
channels:
  - defaults
dependencies:
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cloudpickle
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - ffmpeg
  - fontconfig
  - freetype
  - gettext
  - glib
  - graphite2
  - harfbuzz
  - hdf5
  - icu
  - imageio
  - intel-openmp
  - jasper
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libopencv
  - libopus
  - libpng
  - libtiff
  - libvpx
  - libxml2
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pcre
  - pillow
  - pip
  - pixman
  - pyparsing
  - python=3.7.3
  - python-dateutil
  - pytz
  - pywavelets
  - readline
  - scikit-image
  - scikit-learn
  - scipy=1.2.1
  - setuptools
  - six
  - sqlite
  - tk
  - toolz
  - tornado
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - img2pdf
    - pyside2
    - shiboken2

