name: cbn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - cairo=1.14.12
  - certifi=2019.6.16
  - clangdev=8.0.0
  - cloudpickle=1.2.1
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.1.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.4
  - jasper=2.0.14
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.32
  - llvmdev=8.0.0
  - matplotlib=3.1.0
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - networkx=2.3
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pcre=8.43
  - pillow=6.1.0
  - pip=19.1.1
  - pixman=0.38.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyside2=5.9.0a1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywavelets=1.0.3
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - img2pdf==0.3.3
    - shiboken2==5.12.2

