name: cbn
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pillow
  - pip
  - pyparsing
  - pyside2=5.9.0a1
  - python=3.7.3
  - qt=5.9.7
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools

  - pip:
    - img2pdf==0.3.3
    - shiboken2==5.12.2
