name: cbn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - clangdev
  - cloudpickle
  - cycler
  - cytoolz
  - dask-core
  - dbus
  - decorator
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - gettext
  - glib
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - imageio
  - intel-openmp
  - jasper
  - joblib
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libopencv
  - libopus
  - libpng
  - libtiff
  - libuuid
  - libvpx
  - libxcb
  - libxml2
  - libxslt
  - llvmdev
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pcre
  - pillow
  - pip
  - pixman
  - pyparsing
  - pyside2=5.9.0a1
  - python=3.7.3
  - python-dateutil
  - pytz
  - pywavelets
  - qt=5.9.7
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - toolz
  - tornado
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - img2pdf==0.3.3
    - shiboken2==5.12.2
