# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sat May  4 19:21:33 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from sys import platform

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutLeft = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft.setSpacing(6)
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.labelOpenPhoto = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOpenPhoto.sizePolicy().hasHeightForWidth())
        self.labelOpenPhoto.setSizePolicy(sizePolicy)
        self.labelOpenPhoto.setMinimumSize(QtCore.QSize(0, 22))
        self.labelOpenPhoto.setMaximumSize(QtCore.QSize(16777215, 22))
        self.labelOpenPhoto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOpenPhoto.setObjectName("labelOpenPhoto")
        self.verticalLayoutLeft.addWidget(self.labelOpenPhoto)
        self.labelNumberOfColors = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNumberOfColors.sizePolicy().hasHeightForWidth())
        self.labelNumberOfColors.setSizePolicy(sizePolicy)
        self.labelNumberOfColors.setMinimumSize(QtCore.QSize(0, 26))
        self.labelNumberOfColors.setMaximumSize(QtCore.QSize(16777215, 26))
        self.labelNumberOfColors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelNumberOfColors.setObjectName("labelNumberOfColors")
        self.verticalLayoutLeft.addWidget(self.labelNumberOfColors)
        self.labelPrintSize = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPrintSize.sizePolicy().hasHeightForWidth())
        self.labelPrintSize.setSizePolicy(sizePolicy)
        self.labelPrintSize.setMinimumSize(QtCore.QSize(0, 26))
        self.labelPrintSize.setMaximumSize(QtCore.QSize(16777215, 26))
        self.labelPrintSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPrintSize.setObjectName("labelPrintSize")
        self.verticalLayoutLeft.addWidget(self.labelPrintSize)
        self.labelMinSurfaceSize = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMinSurfaceSize.sizePolicy().hasHeightForWidth())
        self.labelMinSurfaceSize.setSizePolicy(sizePolicy)
        self.labelMinSurfaceSize.setMinimumSize(QtCore.QSize(0, 24))
        self.labelMinSurfaceSize.setMaximumSize(QtCore.QSize(16777215, 24))
        self.labelMinSurfaceSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMinSurfaceSize.setObjectName("labelMinSurfaceSize")
        self.verticalLayoutLeft.addWidget(self.labelMinSurfaceSize)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutLeft.addItem(spacerItem)
        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayoutLeft.addWidget(self.pushButtonStart)
        self.horizontalLayout.addLayout(self.verticalLayoutLeft)
        self.verticalLayoutRight = QtWidgets.QVBoxLayout()
        if platform == "darwin":
            self.verticalLayoutRight.setSpacing(8)
        else:
            self.verticalLayoutRight.setSpacing(6)
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")
        self.toolButtonOpenPhoto = QtWidgets.QToolButton(self.centralwidget)
        self.toolButtonOpenPhoto.setMinimumSize(QtCore.QSize(0, 22))
        self.toolButtonOpenPhoto.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toolButtonOpenPhoto.setObjectName("toolButtonOpenPhoto")
        self.verticalLayoutRight.addWidget(self.toolButtonOpenPhoto)
        self.spinBoxNumberOfColors = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxNumberOfColors.sizePolicy().hasHeightForWidth())
        self.spinBoxNumberOfColors.setSizePolicy(sizePolicy)
        self.spinBoxNumberOfColors.setMinimumSize(QtCore.QSize(0, 26))
        self.spinBoxNumberOfColors.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBoxNumberOfColors.setMinimum(1)
        self.spinBoxNumberOfColors.setMaximum(100)
        self.spinBoxNumberOfColors.setProperty("value", 20)
        self.spinBoxNumberOfColors.setObjectName("spinBoxNumberOfColors")
        self.verticalLayoutRight.addWidget(self.spinBoxNumberOfColors)
        self.comboBoxPrintSize = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPrintSize.sizePolicy().hasHeightForWidth())
        self.comboBoxPrintSize.setSizePolicy(sizePolicy)
        self.comboBoxPrintSize.setMinimumSize(QtCore.QSize(0, 26))
        self.comboBoxPrintSize.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBoxPrintSize.setObjectName("comboBoxPrintSize")
        self.comboBoxPrintSize.addItem("")
        self.comboBoxPrintSize.addItem("")
        self.comboBoxPrintSize.addItem("")
        self.comboBoxPrintSize.addItem("")
        self.comboBoxPrintSize.addItem("")
        self.verticalLayoutRight.addWidget(self.comboBoxPrintSize)
        self.spinBoxMinSurfaceSize = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxMinSurfaceSize.sizePolicy().hasHeightForWidth())
        self.spinBoxMinSurfaceSize.setSizePolicy(sizePolicy)
        self.spinBoxMinSurfaceSize.setMinimumSize(QtCore.QSize(0, 24))
        self.spinBoxMinSurfaceSize.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBoxMinSurfaceSize.setMinimum(1)
        self.spinBoxMinSurfaceSize.setMaximum(100)
        self.spinBoxMinSurfaceSize.setProperty("value", 20)
        self.spinBoxMinSurfaceSize.setObjectName("spinBoxMinSurfaceSize")
        self.verticalLayoutRight.addWidget(self.spinBoxMinSurfaceSize)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutRight.addItem(spacerItem1)
        self.pushButtonExport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.verticalLayoutRight.addWidget(self.pushButtonExport)
        self.horizontalLayout.addLayout(self.verticalLayoutRight)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Color Photo By Number", None, -1))
        self.labelOpenPhoto.setText(QtWidgets.QApplication.translate("MainWindow", "open photo", None, -1))
        self.labelNumberOfColors.setText(QtWidgets.QApplication.translate("MainWindow", "number of colors", None, -1))
        self.labelPrintSize.setText(QtWidgets.QApplication.translate("MainWindow", "print size", None, -1))
        self.labelMinSurfaceSize.setText(QtWidgets.QApplication.translate("MainWindow", "min. surface size", None, -1))
        self.pushButtonStart.setText(QtWidgets.QApplication.translate("MainWindow", "start", None, -1))
        self.toolButtonOpenPhoto.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.comboBoxPrintSize.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "DIN A1", None, -1))
        self.comboBoxPrintSize.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "DIN A2", None, -1))
        self.comboBoxPrintSize.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "DIN A3", None, -1))
        self.comboBoxPrintSize.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "DIN A4", None, -1))
        self.comboBoxPrintSize.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "DIN A5", None, -1))
        self.comboBoxPrintSize.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "DIN A4", None, -1))
        self.pushButtonExport.setText(QtWidgets.QApplication.translate("MainWindow", "export ...", None, -1))